root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  full_bin = "air-full"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  log = "air.log"

[run]
  # We can pass arguments to our app here
  # E.g., cmd = "./tmp/main --port 8080"

[log]
  time = true

[color]
  main = "yellow"
  runner = "green"
  watcher = "cyan"
  build = "blue"
  app = "magenta"