version: '3.8'

services:
  db-primary: # Antes era 'db'
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet
    ports:
      - "5432:5432" # Puerto del primario
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data

  db-replica: # Nuevo servicio para la réplica
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet
    ports:
      - "5433:5432" # Exponemos en un puerto diferente para no chocar
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db-primary
      - db-replica
      - redis
    env_file:
      - .env

volumes:
  postgres_primary_data:
  postgres_replica_data: